services:
    users-serv:
        container_name: users-con
        command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
        restart: always
        build:
            context: ./users
            dockerfile: Dockerfile
        env_file:
          - ./users/.env
        volumes:
          - ./users:/app
        depends_on:
          - users-db-serv
          - rabbitmq
        networks:
          - global-network
        ports:
          - "8080:80"

    users-db-serv:
        image: postgres:latest
        container_name: users-db-con
        restart: unless-stopped
        environment:
            POSTGRES_USER: users_db_user
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: users_db
        volumes:
          - postgres_data:/var/lib/postgresql/data
        networks:
          - global-network

    notification-serv:
        container_name: notification-con
        command: python main.py
        restart: unless-stopped
        build:
            context: ./notification
            dockerfile: Dockerfile
        env_file:
            - ./notification/.env
        volumes:
            - ./notification:/app
        networks:
            - global-network
        depends_on:
            - rabbitmq
            - users-serv

    rabbitmq:
        container_name: rabbitmq-con
        image: rabbitmq:4.0.6-alpine
        restart: unless-stopped
        environment:
            - RABBITMQ_ENABLED_PLUGINS=[]
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - global-network

volumes:
    postgres_data:
    rabbitmq_data:

networks:
    global-network:
        driver: bridge
