services:
    users-serv:
        container_name: users-test-con
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.test
        env_file:
             .env
        depends_on:
            - users-test-db-serv
        networks:
            - network

    users-test-db-serv:
        image: postgres:17.4-alpine
        container_name: users-test-db-con
        restart: unless-stopped
        environment:
            POSTGRES_USER: users_test_db_user
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: users__test_db
        networks:
            - network

networks:
    network:
        driver: bridge
