FROM python:3.12.3-slim

ENV PYTHONDONTWRITEBYTECODE = 1
ENV PYTHONBUFFERED = 1

WORKDIR /app

RUN apt-get update && apt-get install -y git

COPY ./requirements.txt /app
RUN pip install --no-cache-dir --upgrade -r requirements-dev.txt

COPY . /app

RUN alembic -c alembic.ini revision --autogenerate

RUN alembic -c alembic.ini upgrade head

CMD ["pytest", "-v"]
